"""Feature definitions for CI/DevOps domain."""

from typing import Dict

from app.tasks.pipeline.feature_dag._types import (
    FeatureCategory,
    FeatureDataType,
    FeatureDefinition,
    FeatureResource,
    OutputFormat,
)

CI_FEATURES: Dict[str, FeatureDefinition] = {
    # === DevOps ===
    "devops_files_changed": FeatureDefinition(
        name="devops_files_changed",
        display_name="DevOps Files Changed",
        description="Count of DevOps/CI configuration files changed in build",
        category=FeatureCategory.DEVOPS,
        data_type=FeatureDataType.INTEGER,
        extractor_node="ci",
        required_resources=[FeatureResource.GIT_HISTORY],
    ),
    "devops_lines_changed": FeatureDefinition(
        name="devops_lines_changed",
        display_name="DevOps Change Size",
        description="Total lines changed in DevOps files",
        category=FeatureCategory.DEVOPS,
        data_type=FeatureDataType.INTEGER,
        extractor_node="ci",
        required_resources=[FeatureResource.GIT_HISTORY],
    ),
    "devops_tools_detected": FeatureDefinition(
        name="devops_tools_detected",
        display_name="DevOps Tools",
        description="List of DevOps tools detected (Docker, K8s, etc.)",
        category=FeatureCategory.DEVOPS,
        data_type=FeatureDataType.LIST_STRING,
        extractor_node="ci",
        required_resources=[FeatureResource.GIT_HISTORY],
        output_format=OutputFormat.COMMA_SEPARATED,
    ),
    # === Build Logs ===
    "log_test_frameworks": FeatureDefinition(
        name="log_test_frameworks",
        display_name="Test Frameworks",
        description="List of detected test frameworks",
        category=FeatureCategory.BUILD_LOG,
        data_type=FeatureDataType.LIST_STRING,
        extractor_node="ci",
        required_resources=[FeatureResource.BUILD_LOGS],
        output_format=OutputFormat.COMMA_SEPARATED,
    ),
    "log_tests_run": FeatureDefinition(
        name="log_tests_run",
        display_name="Tests Run",
        description="Total tests run across all jobs",
        category=FeatureCategory.BUILD_LOG,
        data_type=FeatureDataType.INTEGER,
        extractor_node="ci",
        required_resources=[FeatureResource.BUILD_LOGS],
    ),
    "log_tests_failed": FeatureDefinition(
        name="log_tests_failed",
        display_name="Tests Failed",
        description="Total tests failed across all jobs",
        category=FeatureCategory.BUILD_LOG,
        data_type=FeatureDataType.INTEGER,
        extractor_node="ci",
        required_resources=[FeatureResource.BUILD_LOGS],
    ),
    "log_tests_skipped": FeatureDefinition(
        name="log_tests_skipped",
        display_name="Tests Skipped",
        description="Total tests skipped across all jobs",
        category=FeatureCategory.BUILD_LOG,
        data_type=FeatureDataType.INTEGER,
        extractor_node="ci",
        required_resources=[FeatureResource.BUILD_LOGS],
    ),
    "log_tests_passed": FeatureDefinition(
        name="log_tests_passed",
        display_name="Tests Passed",
        description="Total tests passed across all jobs",
        category=FeatureCategory.BUILD_LOG,
        data_type=FeatureDataType.INTEGER,
        extractor_node="ci",
        required_resources=[FeatureResource.BUILD_LOGS],
    ),
    "log_tests_fail_rate": FeatureDefinition(
        name="log_tests_fail_rate",
        display_name="Test Fail Rate",
        description="Failure rate (failed / run)",
        category=FeatureCategory.BUILD_LOG,
        data_type=FeatureDataType.FLOAT,
        extractor_node="ci",
        required_resources=[FeatureResource.BUILD_LOGS],
        valid_range=(0.0, 1.0),
    ),
    "log_test_duration_sec": FeatureDefinition(
        name="log_test_duration_sec",
        display_name="Test Duration",
        description="Total test duration in seconds",
        category=FeatureCategory.BUILD_LOG,
        data_type=FeatureDataType.FLOAT,
        extractor_node="ci",
        required_resources=[FeatureResource.BUILD_LOGS],
        unit="seconds",
    ),
    "log_jobs_count": FeatureDefinition(
        name="log_jobs_count",
        display_name="Number of Jobs",
        description="Number of job logs parsed from CI build",
        category=FeatureCategory.BUILD_LOG,
        data_type=FeatureDataType.INTEGER,
        extractor_node="ci",
        required_resources=[FeatureResource.BUILD_LOGS],
    ),
    "log_job_ids": FeatureDefinition(
        name="log_job_ids",
        display_name="Job IDs",
        description="IDs of jobs in the CI build, comma-separated",
        category=FeatureCategory.BUILD_LOG,
        data_type=FeatureDataType.STRING,
        extractor_node="ci",
        required_resources=[FeatureResource.BUILD_LOGS],
    ),
}
