"""Feature definitions for Ci domain."""

from typing import Dict

from app.tasks.pipeline.feature_dag._types import (
    FeatureCategory,
    FeatureDataType,
    FeatureDefinition,
    FeatureResource,
    OutputFormat,
)

CI_FEATURES: Dict[str, FeatureDefinition] = {
    "num_of_devops_files": FeatureDefinition(
        name="num_of_devops_files",
        display_name="DevOps Files Changed",
        description="Count of DevOps/CI configuration files changed in build",
        category=FeatureCategory.DEVOPS,
        data_type=FeatureDataType.INTEGER,
        extractor_node="ci",
        required_resources=[FeatureResource.GIT_HISTORY],
    ),
    "devops_change_size": FeatureDefinition(
        name="devops_change_size",
        display_name="DevOps Change Size",
        description="Total lines changed in DevOps files",
        category=FeatureCategory.DEVOPS,
        data_type=FeatureDataType.INTEGER,
        extractor_node="ci",
        required_resources=[FeatureResource.GIT_HISTORY],
    ),
    "devops_tools_used": FeatureDefinition(
        name="devops_tools_used",
        display_name="DevOps Tools",
        description="List of DevOps tools detected (Docker, K8s, etc.)",
        category=FeatureCategory.DEVOPS,
        data_type=FeatureDataType.LIST_STRING,
        extractor_node="ci",
        required_resources=[FeatureResource.GIT_HISTORY],
        output_format=OutputFormat.COMMA_SEPARATED,
    ),
    "tr_log_frameworks_all": FeatureDefinition(
        name="tr_log_frameworks_all",
        display_name="Test Frameworks",
        description="List of detected test frameworks",
        category=FeatureCategory.BUILD_LOG,
        data_type=FeatureDataType.LIST_STRING,
        extractor_node="ci",
        required_resources=[FeatureResource.BUILD_LOGS],
        output_format=OutputFormat.COMMA_SEPARATED,
    ),
    "tr_log_tests_run_sum": FeatureDefinition(
        name="tr_log_tests_run_sum",
        display_name="Tests Run",
        description="Total tests run across all jobs",
        category=FeatureCategory.BUILD_LOG,
        data_type=FeatureDataType.INTEGER,
        extractor_node="ci",
        required_resources=[FeatureResource.BUILD_LOGS],
    ),
    "tr_log_tests_failed_sum": FeatureDefinition(
        name="tr_log_tests_failed_sum",
        display_name="Tests Failed",
        description="Total tests failed across all jobs",
        category=FeatureCategory.BUILD_LOG,
        data_type=FeatureDataType.INTEGER,
        extractor_node="ci",
        required_resources=[FeatureResource.BUILD_LOGS],
    ),
    "tr_log_tests_skipped_sum": FeatureDefinition(
        name="tr_log_tests_skipped_sum",
        display_name="Tests Skipped",
        description="Total tests skipped across all jobs",
        category=FeatureCategory.BUILD_LOG,
        data_type=FeatureDataType.INTEGER,
        extractor_node="ci",
        required_resources=[FeatureResource.BUILD_LOGS],
    ),
    "tr_log_tests_ok_sum": FeatureDefinition(
        name="tr_log_tests_ok_sum",
        display_name="Tests Passed",
        description="Total tests passed across all jobs",
        category=FeatureCategory.BUILD_LOG,
        data_type=FeatureDataType.INTEGER,
        extractor_node="ci",
        required_resources=[FeatureResource.BUILD_LOGS],
    ),
    "tr_log_tests_fail_rate": FeatureDefinition(
        name="tr_log_tests_fail_rate",
        display_name="Test Fail Rate",
        description="Failure rate (failed / run)",
        category=FeatureCategory.BUILD_LOG,
        data_type=FeatureDataType.FLOAT,
        extractor_node="ci",
        required_resources=[FeatureResource.BUILD_LOGS],
        valid_range=(0.0, 1.0),
    ),
    "tr_log_testduration_sum": FeatureDefinition(
        name="tr_log_testduration_sum",
        display_name="Test Duration",
        description="Total test duration in seconds",
        category=FeatureCategory.BUILD_LOG,
        data_type=FeatureDataType.FLOAT,
        extractor_node="ci",
        required_resources=[FeatureResource.BUILD_LOGS],
        unit="seconds",
    ),
    "tr_log_num_jobs": FeatureDefinition(
        name="tr_log_num_jobs",
        display_name="Number of Jobs",
        description="Number of job logs parsed from CI build",
        category=FeatureCategory.BUILD_LOG,
        data_type=FeatureDataType.INTEGER,
        extractor_node="ci",
        required_resources=[FeatureResource.BUILD_LOGS],
    ),
    "tr_jobs": FeatureDefinition(
        name="tr_jobs",
        display_name="Job IDs",
        description="IDs of jobs in the CI build, comma-separated",
        category=FeatureCategory.BUILD_LOG,
        data_type=FeatureDataType.STRING,
        extractor_node="ci",
        required_resources=[FeatureResource.BUILD_LOGS],
    ),
}
