"""Feature definitions for Code/Git domain."""

from typing import Dict

from app.tasks.pipeline.feature_dag._types import (
    FeatureCategory,
    FeatureDataType,
    FeatureDefinition,
    FeatureResource,
    OutputFormat,
)

CODE_FEATURES: Dict[str, FeatureDefinition] = {
    # === Git Commit Info ===
    "git_trigger_sha": FeatureDefinition(
        name="git_trigger_sha",
        display_name="Trigger Commit SHA",
        description="Commit SHA that triggered the build",
        category=FeatureCategory.GIT_HISTORY,
        data_type=FeatureDataType.STRING,
        extractor_node="code",
        required_resources=[FeatureResource.BUILD_RUN],
    ),
    "git_branch": FeatureDefinition(
        name="git_branch",
        display_name="Branch",
        description="Branch name that triggered the build",
        category=FeatureCategory.GIT_HISTORY,
        data_type=FeatureDataType.STRING,
        extractor_node="code",
        required_resources=[FeatureResource.BUILD_RUN],
    ),
    "git_built_commits": FeatureDefinition(
        name="git_built_commits",
        display_name="All Built Commits",
        description="List of commit SHAs included in this build",
        category=FeatureCategory.GIT_HISTORY,
        data_type=FeatureDataType.LIST_STRING,
        extractor_node="code",
        required_resources=[
            FeatureResource.GIT_HISTORY,
            FeatureResource.RAW_BUILD_RUNS,
        ],
        output_format=OutputFormat.HASH_SEPARATED,
    ),
    "git_built_commits_count": FeatureDefinition(
        name="git_built_commits_count",
        display_name="Number of Built Commits",
        description="Count of commits included in this build",
        category=FeatureCategory.GIT_HISTORY,
        data_type=FeatureDataType.INTEGER,
        extractor_node="code",
        required_resources=[
            FeatureResource.GIT_HISTORY,
            FeatureResource.RAW_BUILD_RUNS,
        ],
    ),
    "git_prev_commit_sha": FeatureDefinition(
        name="git_prev_commit_sha",
        display_name="Previous Built Commit",
        description="SHA of last commit that was built",
        category=FeatureCategory.GIT_HISTORY,
        data_type=FeatureDataType.STRING,
        extractor_node="code",
        required_resources=[
            FeatureResource.GIT_HISTORY,
            FeatureResource.RAW_BUILD_RUNS,
        ],
        nullable=True,
    ),
    "git_prev_commit_status": FeatureDefinition(
        name="git_prev_commit_status",
        display_name="Previous Commit Resolution",
        description="How previous commit was resolved",
        category=FeatureCategory.GIT_HISTORY,
        data_type=FeatureDataType.STRING,
        extractor_node="code",
        required_resources=[
            FeatureResource.GIT_HISTORY,
            FeatureResource.RAW_BUILD_RUNS,
        ],
        valid_values=[
            "build_found",
            "merge_found",
            "no_previous_build",
            "commit_not_found",
        ],
    ),
    # === Git Diff Stats ===
    "git_diff_src_churn": FeatureDefinition(
        name="git_diff_src_churn",
        display_name="Source Code Churn",
        description="Lines added + deleted in source files",
        category=FeatureCategory.GIT_DIFF,
        data_type=FeatureDataType.INTEGER,
        extractor_node="code",
        required_resources=[FeatureResource.GIT_HISTORY],
    ),
    "git_diff_test_churn": FeatureDefinition(
        name="git_diff_test_churn",
        display_name="Test Code Churn",
        description="Lines added + deleted in test files",
        category=FeatureCategory.GIT_DIFF,
        data_type=FeatureDataType.INTEGER,
        extractor_node="code",
        required_resources=[FeatureResource.GIT_HISTORY],
    ),
    "git_diff_files_added": FeatureDefinition(
        name="git_diff_files_added",
        display_name="Files Added",
        description="Number of files added in this build",
        category=FeatureCategory.GIT_DIFF,
        data_type=FeatureDataType.INTEGER,
        extractor_node="code",
        required_resources=[FeatureResource.GIT_HISTORY],
    ),
    "git_diff_files_deleted": FeatureDefinition(
        name="git_diff_files_deleted",
        display_name="Files Deleted",
        description="Number of files deleted in this build",
        category=FeatureCategory.GIT_DIFF,
        data_type=FeatureDataType.INTEGER,
        extractor_node="code",
        required_resources=[FeatureResource.GIT_HISTORY],
    ),
    "git_diff_files_modified": FeatureDefinition(
        name="git_diff_files_modified",
        display_name="Files Modified",
        description="Number of files modified in this build",
        category=FeatureCategory.GIT_DIFF,
        data_type=FeatureDataType.INTEGER,
        extractor_node="code",
        required_resources=[FeatureResource.GIT_HISTORY],
    ),
    "git_diff_tests_added": FeatureDefinition(
        name="git_diff_tests_added",
        display_name="Tests Added",
        description="Number of test cases added",
        category=FeatureCategory.GIT_DIFF,
        data_type=FeatureDataType.INTEGER,
        extractor_node="code",
        required_resources=[FeatureResource.GIT_HISTORY],
    ),
    "git_diff_tests_deleted": FeatureDefinition(
        name="git_diff_tests_deleted",
        display_name="Tests Deleted",
        description="Number of test cases deleted",
        category=FeatureCategory.GIT_DIFF,
        data_type=FeatureDataType.INTEGER,
        extractor_node="code",
        required_resources=[FeatureResource.GIT_HISTORY],
    ),
    "git_diff_src_files": FeatureDefinition(
        name="git_diff_src_files",
        display_name="Source Files Changed",
        description="Number of source files changed",
        category=FeatureCategory.GIT_DIFF,
        data_type=FeatureDataType.INTEGER,
        extractor_node="code",
        required_resources=[FeatureResource.GIT_HISTORY],
    ),
    "git_diff_doc_files": FeatureDefinition(
        name="git_diff_doc_files",
        display_name="Doc Files Changed",
        description="Number of documentation files changed",
        category=FeatureCategory.GIT_DIFF,
        data_type=FeatureDataType.INTEGER,
        extractor_node="code",
        required_resources=[FeatureResource.GIT_HISTORY],
    ),
    "git_diff_other_files": FeatureDefinition(
        name="git_diff_other_files",
        display_name="Other Files Changed",
        description="Number of other files changed (not source or doc)",
        category=FeatureCategory.GIT_DIFF,
        data_type=FeatureDataType.INTEGER,
        extractor_node="code",
        required_resources=[FeatureResource.GIT_HISTORY],
    ),
    "git_file_commit_density": FeatureDefinition(
        name="git_file_commit_density",
        display_name="File Commit Density",
        description="Number of commits that touched files modified in this build (last N days)",
        category=FeatureCategory.GIT_HISTORY,
        data_type=FeatureDataType.INTEGER,
        extractor_node="code",
        required_resources=[FeatureResource.GIT_HISTORY, FeatureResource.BUILD_RUN],
    ),
    "git_change_entropy": FeatureDefinition(
        name="git_change_entropy",
        display_name="Change Entropy",
        description="Entropy of file changes in the build",
        category=FeatureCategory.GIT_DIFF,
        data_type=FeatureDataType.FLOAT,
        extractor_node="code",
        required_resources=[FeatureResource.GIT_HISTORY],
    ),
    "git_files_modified_ratio": FeatureDefinition(
        name="git_files_modified_ratio",
        display_name="Files Modified Ratio",
        description="Ratio of modified files to total changed files",
        category=FeatureCategory.GIT_DIFF,
        data_type=FeatureDataType.FLOAT,
        extractor_node="code",
        required_resources=[FeatureResource.GIT_HISTORY],
        valid_range=(0.0, 1.0),
    ),
    "git_churn_vs_avg": FeatureDefinition(
        name="git_churn_vs_avg",
        display_name="Churn vs Average",
        description="Current churn relative to project average",
        category=FeatureCategory.GIT_DIFF,
        data_type=FeatureDataType.FLOAT,
        extractor_node="code",
        required_resources=[
            FeatureResource.GIT_HISTORY,
            FeatureResource.RAW_BUILD_RUNS,
        ],
    ),
    # === Team Metrics ===
    "team_size": FeatureDefinition(
        name="team_size",
        display_name="Team Size",
        description="Number of unique contributors in last 90 days",
        category=FeatureCategory.TEAM,
        data_type=FeatureDataType.INTEGER,
        extractor_node="code",
        required_resources=[
            FeatureResource.GIT_HISTORY,
            FeatureResource.RAW_BUILD_RUNS,
        ],
    ),
    "team_is_core_member": FeatureDefinition(
        name="team_is_core_member",
        display_name="By Core Team Member",
        description="Whether build author is a core team member",
        category=FeatureCategory.TEAM,
        data_type=FeatureDataType.BOOLEAN,
        extractor_node="code",
        required_resources=[
            FeatureResource.GIT_HISTORY,
            FeatureResource.RAW_BUILD_RUNS,
        ],
    ),
    "team_distinct_authors": FeatureDefinition(
        name="team_distinct_authors",
        display_name="Distinct Authors",
        description="Number of unique commit authors in this build",
        category=FeatureCategory.TEAM,
        data_type=FeatureDataType.INTEGER,
        extractor_node="code",
        required_resources=[FeatureResource.GIT_HISTORY],
    ),
    "team_total_revisions": FeatureDefinition(
        name="team_total_revisions",
        display_name="Total File Revisions",
        description="Total number of prior revisions on files touched by this build",
        category=FeatureCategory.COOPERATION,
        data_type=FeatureDataType.INTEGER,
        extractor_node="code",
        required_resources=[FeatureResource.GIT_HISTORY],
    ),
}
