"""Feature definitions for Repository domain."""

from typing import Dict

from app.tasks.pipeline.feature_dag._types import (
    FeatureCategory,
    FeatureDataType,
    FeatureDefinition,
    FeatureResource,
)

REPOSITORY_FEATURES: Dict[str, FeatureDefinition] = {
    # === PR Discussion ===
    "pr_issue_comments": FeatureDefinition(
        name="pr_issue_comments",
        display_name="Issue Comments",
        description="Number of issue/discussion comments on the PR",
        category=FeatureCategory.DISCUSSION,
        data_type=FeatureDataType.INTEGER,
        extractor_node="repository",
        required_resources=[FeatureResource.GITHUB_API, FeatureResource.BUILD_RUN],
    ),
    "pr_commit_comments": FeatureDefinition(
        name="pr_commit_comments",
        display_name="Commit Comments",
        description="Number of comments on commits in this build",
        category=FeatureCategory.DISCUSSION,
        data_type=FeatureDataType.INTEGER,
        extractor_node="repository",
        required_resources=[FeatureResource.GITHUB_API],
    ),
    "pr_review_comments": FeatureDefinition(
        name="pr_review_comments",
        display_name="PR Review Comments",
        description="Number of code review comments on the PR",
        category=FeatureCategory.DISCUSSION,
        data_type=FeatureDataType.INTEGER,
        extractor_node="repository",
        required_resources=[FeatureResource.GITHUB_API, FeatureResource.BUILD_RUN],
    ),
    "pr_description_words": FeatureDefinition(
        name="pr_description_words",
        display_name="Description Complexity",
        description="Word count of PR title + body",
        category=FeatureCategory.DISCUSSION,
        data_type=FeatureDataType.INTEGER,
        extractor_node="repository",
        required_resources=[FeatureResource.GITHUB_API],
        nullable=True,
    ),
    # === Repository Stats ===
    "repo_age_days": FeatureDefinition(
        name="repo_age_days",
        display_name="Repository Age",
        description="Repository age in days (from first commit to build commit)",
        category=FeatureCategory.REPO_SNAPSHOT,
        data_type=FeatureDataType.FLOAT,
        extractor_node="repository",
        required_resources=[FeatureResource.GIT_HISTORY],
        unit="days",
    ),
    "repo_total_commits": FeatureDefinition(
        name="repo_total_commits",
        display_name="Total Commits",
        description="Total number of commits in repository history",
        category=FeatureCategory.REPO_SNAPSHOT,
        data_type=FeatureDataType.INTEGER,
        extractor_node="repository",
        required_resources=[FeatureResource.GIT_HISTORY],
    ),
    "repo_sloc": FeatureDefinition(
        name="repo_sloc",
        display_name="Source Lines of Code",
        description="Total source lines of code (excluding comments)",
        category=FeatureCategory.REPO_SNAPSHOT,
        data_type=FeatureDataType.INTEGER,
        extractor_node="repository",
        required_resources=[FeatureResource.GIT_WORKTREE],
        nullable=True,
    ),
    "repo_test_lines_per_kloc": FeatureDefinition(
        name="repo_test_lines_per_kloc",
        display_name="Test Lines / KLOC",
        description="Test lines per 1000 lines of source code",
        category=FeatureCategory.REPO_SNAPSHOT,
        data_type=FeatureDataType.FLOAT,
        extractor_node="repository",
        required_resources=[FeatureResource.GIT_WORKTREE],
        nullable=True,
    ),
    "repo_test_cases_per_kloc": FeatureDefinition(
        name="repo_test_cases_per_kloc",
        display_name="Test Cases / KLOC",
        description="Test cases per 1000 lines of source code",
        category=FeatureCategory.REPO_SNAPSHOT,
        data_type=FeatureDataType.FLOAT,
        extractor_node="repository",
        required_resources=[FeatureResource.GIT_WORKTREE],
        nullable=True,
    ),
    "repo_asserts_per_kloc": FeatureDefinition(
        name="repo_asserts_per_kloc",
        display_name="Assertions / KLOC",
        description="Assertions per 1000 lines of source code",
        category=FeatureCategory.REPO_SNAPSHOT,
        data_type=FeatureDataType.FLOAT,
        extractor_node="repository",
        required_resources=[FeatureResource.GIT_WORKTREE],
        nullable=True,
    ),
}
