"""Feature definitions for Temporal/History domain."""

from typing import Dict

from app.tasks.pipeline.feature_dag._types import (
    FeatureCategory,
    FeatureDataType,
    FeatureDefinition,
    FeatureResource,
)

TEMPORAL_FEATURES: Dict[str, FeatureDefinition] = {
    # === Build History ===
    "history_prev_build_id": FeatureDefinition(
        name="history_prev_build_id",
        display_name="Previous Build ID",
        description="ID of the previous build for this commit chain",
        category=FeatureCategory.BUILD_HISTORY,
        data_type=FeatureDataType.STRING,
        extractor_node="temporal",
        required_resources=[
            FeatureResource.GIT_HISTORY,
            FeatureResource.RAW_BUILD_RUNS,
        ],
        nullable=True,
    ),
    "history_prev_result": FeatureDefinition(
        name="history_prev_result",
        display_name="Previous Build Result",
        description="Outcome of the previous build (passed, failed, etc.)",
        category=FeatureCategory.BUILD_HISTORY,
        data_type=FeatureDataType.STRING,
        extractor_node="temporal",
        required_resources=[FeatureResource.RAW_BUILD_RUNS, FeatureResource.BUILD_RUN],
        nullable=True,
    ),
    "history_same_committer": FeatureDefinition(
        name="history_same_committer",
        display_name="Same Committer",
        description="Whether committer is same as previous build",
        category=FeatureCategory.BUILD_HISTORY,
        data_type=FeatureDataType.BOOLEAN,
        extractor_node="temporal",
        required_resources=[FeatureResource.RAW_BUILD_RUNS, FeatureResource.BUILD_RUN],
    ),
    "history_days_since_prev": FeatureDefinition(
        name="history_days_since_prev",
        display_name="Time Since Previous Build",
        description="Days since previous build completed",
        category=FeatureCategory.BUILD_HISTORY,
        data_type=FeatureDataType.FLOAT,
        extractor_node="temporal",
        required_resources=[FeatureResource.RAW_BUILD_RUNS, FeatureResource.BUILD_RUN],
        unit="days",
        nullable=True,
    ),
    "history_project_fail_rate": FeatureDefinition(
        name="history_project_fail_rate",
        display_name="Project Fail Rate",
        description="Overall fail rate of the project",
        category=FeatureCategory.BUILD_HISTORY,
        data_type=FeatureDataType.FLOAT,
        extractor_node="temporal",
        required_resources=[FeatureResource.RAW_BUILD_RUNS, FeatureResource.BUILD_RUN],
        valid_range=(0.0, 1.0),
    ),
    "history_project_fail_recent": FeatureDefinition(
        name="history_project_fail_recent",
        display_name="Project Recent Fail Rate",
        description="Fail rate in last N builds of the project",
        category=FeatureCategory.BUILD_HISTORY,
        data_type=FeatureDataType.FLOAT,
        extractor_node="temporal",
        required_resources=[FeatureResource.RAW_BUILD_RUNS, FeatureResource.BUILD_RUN],
        valid_range=(0.0, 1.0),
    ),
    "history_prev_failed": FeatureDefinition(
        name="history_prev_failed",
        display_name="Previous Build Failed",
        description="Whether the previous build failed",
        category=FeatureCategory.BUILD_HISTORY,
        data_type=FeatureDataType.BOOLEAN,
        extractor_node="temporal",
        required_resources=[FeatureResource.RAW_BUILD_RUNS, FeatureResource.BUILD_RUN],
        nullable=True,
    ),
    "history_fail_streak": FeatureDefinition(
        name="history_fail_streak",
        display_name="Fail Streak",
        description="Number of consecutive failed builds before this one",
        category=FeatureCategory.BUILD_HISTORY,
        data_type=FeatureDataType.INTEGER,
        extractor_node="temporal",
        required_resources=[FeatureResource.RAW_BUILD_RUNS, FeatureResource.BUILD_RUN],
    ),
    "history_fail_rate_10": FeatureDefinition(
        name="history_fail_rate_10",
        display_name="Fail Rate Last 10",
        description="Failure rate in last 10 builds",
        category=FeatureCategory.BUILD_HISTORY,
        data_type=FeatureDataType.FLOAT,
        extractor_node="temporal",
        required_resources=[FeatureResource.RAW_BUILD_RUNS, FeatureResource.BUILD_RUN],
        valid_range=(0.0, 1.0),
    ),
    "history_avg_churn_5": FeatureDefinition(
        name="history_avg_churn_5",
        display_name="Avg Churn Last 5",
        description="Average source code churn in last 5 builds",
        category=FeatureCategory.BUILD_HISTORY,
        data_type=FeatureDataType.FLOAT,
        extractor_node="temporal",
        required_resources=[FeatureResource.RAW_BUILD_RUNS, FeatureResource.BUILD_RUN],
    ),
    # === Author/Committer ===
    "author_fail_rate": FeatureDefinition(
        name="author_fail_rate",
        display_name="Author Fail Rate",
        description="Overall fail rate of this committer",
        category=FeatureCategory.COMMITTER,
        data_type=FeatureDataType.FLOAT,
        extractor_node="temporal",
        required_resources=[FeatureResource.RAW_BUILD_RUNS, FeatureResource.BUILD_RUN],
        valid_range=(0.0, 1.0),
    ),
    "author_fail_rate_recent": FeatureDefinition(
        name="author_fail_rate_recent",
        display_name="Author Recent Fail Rate",
        description="Fail rate in last N builds by this committer",
        category=FeatureCategory.COMMITTER,
        data_type=FeatureDataType.FLOAT,
        extractor_node="temporal",
        required_resources=[FeatureResource.RAW_BUILD_RUNS, FeatureResource.BUILD_RUN],
        valid_range=(0.0, 1.0),
    ),
    "author_experience": FeatureDefinition(
        name="author_experience",
        display_name="Author Experience",
        description="Average experience of committers (builds per person)",
        category=FeatureCategory.COMMITTER,
        data_type=FeatureDataType.FLOAT,
        extractor_node="temporal",
        required_resources=[FeatureResource.RAW_BUILD_RUNS, FeatureResource.BUILD_RUN],
    ),
    "author_ownership": FeatureDefinition(
        name="author_ownership",
        display_name="Author Ownership",
        description="Percentage of project commits by this author",
        category=FeatureCategory.COMMITTER,
        data_type=FeatureDataType.FLOAT,
        extractor_node="temporal",
        required_resources=[FeatureResource.RAW_BUILD_RUNS, FeatureResource.BUILD_RUN],
        valid_range=(0.0, 1.0),
    ),
    "author_is_new": FeatureDefinition(
        name="author_is_new",
        display_name="New Contributor",
        description="Whether author has fewer than 5 builds in this project",
        category=FeatureCategory.COMMITTER,
        data_type=FeatureDataType.BOOLEAN,
        extractor_node="temporal",
        required_resources=[FeatureResource.RAW_BUILD_RUNS, FeatureResource.BUILD_RUN],
    ),
    "author_days_since_commit": FeatureDefinition(
        name="author_days_since_commit",
        display_name="Days Since Author's Last Commit",
        description="Days since this author's previous build",
        category=FeatureCategory.COMMITTER,
        data_type=FeatureDataType.FLOAT,
        extractor_node="temporal",
        required_resources=[FeatureResource.RAW_BUILD_RUNS, FeatureResource.BUILD_RUN],
        unit="days",
        nullable=True,
    ),
}
